name: ChatHavenCI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22.13.1

      - name: Install Dependencies
        run: |
          rm -r node_modules
          npm install
          npm uninstall --save-dev vitest
          npm install --save-dev vitest

      - name: Fix Vitest Permissions
        run: chmod +x ./node_modules/.bin/vitest

      - name: Run Unit Tests with Vitest
        run: npx vitest run --environment jsdom
